

---
Module 5:Data Collection, Cleaning, Visualization, andAnalysis
Note : All missing values have been handled, object columns have been label encoded, and the dataset now contains only numeric values. The data is fully cleaned and ready for training machine learning models.
---

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
df = pd.read_csv('/content/data.csv')

In [6]:
df

Output hidden; open in https://colab.research.google.com to view.

In [7]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [9]:
df.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [10]:
from sklearn.impute import SimpleImputer

num_imp = SimpleImputer(strategy='mean')
cat_imp = SimpleImputer(strategy='most_frequent')

num_col = df.select_dtypes(include= ['float64', 'int64' ] ).columns
cat_col = df.select_dtypes(exclude= 'object').columns

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in cat_col:
  df[col] = le.fit_transform(df[col])

In [12]:
df

Output hidden; open in https://colab.research.google.com to view.

In [17]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP               0
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         0
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [13]:
df.drop('Market Category', axis  = 1 , inplace = True)

In [14]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine Fuel Type     3
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [15]:
df['Engine Fule Type'].fillna(df['Engine Fule Type'].mode()[0], inplace = True)

KeyError: 'Engine Fule Type'

In [16]:
df['Engine Fuel Type'].fillna(df['Engine Fuel Type'].mode()[0], inplace=True)

In [17]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [18]:
df.dtypes

Make                 object
Model                object
Year                  int64
Engine Fuel Type     object
Engine HP             int64
Engine Cylinders      int64
Transmission Type    object
Driven_Wheels        object
Number of Doors       int64
Vehicle Size         object
Vehicle Style        object
highway MPG           int64
city mpg              int64
Popularity            int64
MSRP                  int64
dtype: object

In [19]:
df

Output hidden; open in https://colab.research.google.com to view.

In [20]:
df[df.select.dtypes(include='object').columns] = df.select_dtypes(include='object').astype('int')

ValueError: invalid literal for int() with base 10: 'BMW'

In [22]:
from sklearn.impute import SimpleImputer


df['Engine HP'] = SimpleImputer(strategy='mean').fit_transform(df[['Engine HP']])
df['Engine Cylinders'] = SimpleImputer(strategy='mean').fit_transform(df[['Engine Cylinders']])
df['Number of Doors'] = SimpleImputer(strategy='mean').fit_transform(df[['Number of Doors']])


df['Engine Fuel Type'].fillna(df['Engine Fuel Type'].mode()[0], inplace=True)

In [24]:
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [25]:
df

Output hidden; open in https://colab.research.google.com to view.

In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col].astype(str))
    df[col] = df[col].astype(int)

In [27]:
df.dtypes()

Make                   int64
Model                  int64
Year                   int64
Engine Fuel Type       int64
Engine HP            float64
Engine Cylinders     float64
Transmission Type      int64
Driven_Wheels          int64
Number of Doors      float64
Vehicle Size           int64
Vehicle Style          int64
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [28]:
df

Output hidden; open in https://colab.research.google.com to view.